### ISSUE TITLE
License details

### ISSUE THREAD

**Issue by ann-2005** [schlafwandler/kcore_dump#1]
What is the License for this program?

**Comment by vt-alt** [comment]
@schlafwandler We want to include `kcore_dump` into unstable branch of ALT Linux distribution. But, without open-source license it's would not be allowed. See,
~~~
  If you find software that doesn’t have a license, that generally means
  you have no permission from the creators of the software to use,
  modify, or share the software. Although a code host such as GitHub may
  allow you to view and fork the code, this does not imply that you are
  permitted to use, modify, or share the software for any purpose.
  -- https://choosealicense.com/no-permission/
~~~
Also, on the subject of handling of non-licensed works https://softwareengineering.stackexchange.com/questions/148146/open-source-code-with-no-license-can-i-fork-it

Can you state some license for it here, please?

Thanks,

**Comment by schlafwandler** [comment]
I've now put it under GPLv3. Does this work for you?

**Comment by vt-alt** [comment]
Yes, thank you very much!
